apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: acmeair-flightservice
spec:
  template:
    metadata:
      labels:
        name: acmeair-flightservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9080"
    spec:
      containers:
        - name: acmeair-flightservice-java
          image: quay.io/dbhagava/quarkus/acmeair-flightservice-quarkus-jvm:v2
          ports:
          - containerPort: 9080
          imagePullPolicy: Always
          env:
          - name: USERNAME
            value: admin
          - name: PASSWORD
            value: password
          - name: MONGO_HOST
            value: acmeair-flight-db
          - name: JAEGER_AGENT_HOST
            value: jaeger-all-in-one-inmemory-agent
          - name: JAEGER_AGENT_PORT
            value: '6832'
          - name: JAEGER_ENDPOINT
            value: 'http://jaeger-all-in-one-inmemory-collector:14268/api/traces'
          - name: ACCESS_LOGGING_ENABLED
            value: 'false'
          - name: TRACE_SPEC
            value: '*=info'
          - name: LOGGING_FORMAT
            value: 'simple'
          readinessProbe:
            httpGet:
              path: /health
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 9080
            initialDelaySeconds: 120
            periodSeconds: 15
